### ISSUE TITLE
is there plans to make uefi version of this? thx

### ISSUE THREAD

**Issue by kocoman1** [Theldus/bread#2]
is there plans to make uefi version of this? thx

**Comment by Theldus** [comment]
Hi @kocoman1,
Unfortunately not, because it is not needed and there is already official support for it, as in [Debug UEFI code by single-stepping your Coffee Lake-S hardware CPU](https://casualhacking.io/blog/2019/6/2/debug-uefi-code-by-single-stepping-your-coffee-lake-s-hardware-cpu).

However, UEFI debugging via DCI is still limited to newer CPUs (Intel 6th gen+) and only Intel (there might be some solution for AMD as well...), so there is still a gap that BREAD could try to fill. However, given the complexity of UEFI and the numerous firmware security mitigations, it's not worth the effort to fill this slice of unsupported hardware.

**Comment by kocoman1** [comment]
I mostly use Ivy Bridge CPU/haswell/boardwell.. thats why I ask..  thank you for replying anyway

**Comment by Theldus** [comment]
I see... my main desktop is a SandyBridge so... no debug either =/.
